/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Cliente;
import bean.Veiculo;
import bean.Veiculo;
import dao.ClienteDao;
import dao.VeiculoDao;
import dao.VeiculoDao;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bjewjb ndfas
 */
public class FormVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormVeiculo
     */
    public FormVeiculo() {
        initComponents();
        this.setVisible(true);
        this.atualizaLista();
        this.atualizaComboCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kmTxt = new javax.swing.JTextField();
        fabricanteTxt = new javax.swing.JTextField();
        anoTxt = new javax.swing.JTextField();
        clienteCombo = new javax.swing.JComboBox();
        salvarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        limpaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        veiculoTable = new javax.swing.JTable();
        relaodButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Veiculos");

        jLabel1.setText("Id");

        idTxt.setEditable(false);

        jLabel2.setText("Proprietario");

        jLabel3.setText("Modelo");

        jLabel4.setText("Ano");

        jLabel5.setText("Fabricante");

        jLabel6.setText("Kilometragem");

        clienteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clienteCombo.setToolTipText("");

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        limpaButton.setText("Limpa");
        limpaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaButtonActionPerformed(evt);
            }
        });

        veiculoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Proprietario", "Modelo", "Fabricante", "Ano", "Kilometragem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        veiculoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veiculoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(veiculoTable);
        if (veiculoTable.getColumnModel().getColumnCount() > 0) {
            veiculoTable.getColumnModel().getColumn(0).setResizable(false);
            veiculoTable.getColumnModel().getColumn(1).setResizable(false);
            veiculoTable.getColumnModel().getColumn(2).setResizable(false);
            veiculoTable.getColumnModel().getColumn(3).setResizable(false);
            veiculoTable.getColumnModel().getColumn(4).setResizable(false);
            veiculoTable.getColumnModel().getColumn(5).setResizable(false);
        }

        relaodButton.setText("Reload");
        relaodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaodButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(clienteCombo, 0, 200, Short.MAX_VALUE)
                                        .addComponent(idTxt))
                                    .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(anoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fabricanteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salvarButton)
                                .addGap(18, 18, 18)
                                .addComponent(excluirButton)
                                .addGap(18, 18, 18)
                                .addComponent(limpaButton)
                                .addGap(205, 205, 205)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(relaodButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(clienteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(modeloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(anoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fabricanteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(excluirButton)
                    .addComponent(limpaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(relaodButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed

        try {
            Veiculo veiculo = new Veiculo();
            veiculo.setFabricante(this.fabricanteTxt.getText());
            veiculo.setModelo(this.modeloTxt.getText());
            veiculo.setAno(Integer.parseInt(this.anoTxt.getText()));
            veiculo.setKm(Integer.parseInt(this.kmTxt.getText()));
            Object obj = this.clienteCombo.getModel().getSelectedItem();
            if (obj instanceof Cliente) {
                veiculo.setCliente((Cliente) obj);
            } else {
                JOptionPane.showMessageDialog(null, "O proprietario do veiculo deve ser informado!!");
                return;
            }
            VeiculoDao veiculodao = new VeiculoDao(ViewSistema.getConexao());
            int cod = this.intCampoTelas(this.idTxt.getText());
            if (cod > 0) {
                veiculo.setId(cod);
                veiculodao.update(veiculo);
                this.atualizaLista();
                this.limpatela();

            } else {

                veiculodao.create(veiculo);
                this.atualizaLista();
                this.limpatela();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Número mal formatado [Ano | Kilometragem]");
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void veiculoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculoTableMouseClicked
        if (evt.getClickCount() > 1) {
            JTable obj = (JTable) evt.getComponent();
            int linha = obj.getSelectedRow();
            Integer cod = (Integer) obj.getModel().getValueAt(linha, 0);
            Veiculo veiculo = new Veiculo(cod);
            this.preencheTela(veiculo);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoTableMouseClicked

    private void relaodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaodButtonActionPerformed
        this.atualizaLista();
    }//GEN-LAST:event_relaodButtonActionPerformed

    private void limpaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaButtonActionPerformed
        this.limpatela();
    }//GEN-LAST:event_limpaButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        int cod = this.intCampoTelas(this.idTxt.getText());
        if (cod > 0) {
            Veiculo veiculoc = new Veiculo(cod);
            VeiculoDao veiculocDao = new VeiculoDao(ViewSistema.getConexao());
            try {
                veiculocDao.delete(veiculoc);
            } catch (SQLException ex) {
                Logger.getLogger(FormVeiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.limpatela();
            this.atualizaLista();
        }
    }//GEN-LAST:event_excluirButtonActionPerformed

    private boolean preencheTela(Veiculo veiculo) {
        boolean ret = false;
        try {
            VeiculoDao veiculoDAO = new VeiculoDao(ViewSistema.getConexao());
            veiculo = veiculoDAO.retrieve(veiculo);
            if (veiculo != null && veiculo.getId() > 0) {
                this.fabricanteTxt.setText(veiculo.getFabricante());
                this.anoTxt.setText(Integer.toString(veiculo.getAno()));
                this.modeloTxt.setText(veiculo.getModelo());
                this.idTxt.setText(Integer.toString(veiculo.getId()));
                this.kmTxt.setText(Integer.toString(veiculo.getKm()));
                this.clienteCombo.setSelectedItem(veiculo.getCliente());
                ret = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, String.format("Não foi possível carregar Funcionário: %s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);

        }
        return ret;
    }

    private void atualizaLista() {
        try {
            VeiculoDao veiculoDAO = new VeiculoDao(ViewSistema.getConexao());
            List<Veiculo> lista = veiculoDAO.listaTodos();
            DefaultTableModel dtm = (DefaultTableModel) this.veiculoTable.getModel();
            dtm.setRowCount(0);
            for (Veiculo veiculo : lista) {
                dtm.addRow(new Object[]{veiculo.getId(), veiculo.getCliente().getNome(), veiculo.getModelo(), veiculo.getFabricante(), veiculo.getAno(), veiculo.getKm()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, String.format("Erro ao ler os Veiculos:%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizaComboCliente() {
        try {
            ClienteDao clienteDAO = new ClienteDao(ViewSistema.getConexao());
            List<Cliente> lista = clienteDAO.listaTodos();
            Vector v = new Vector(lista);
            v.add(0, "");
            ComboBoxModel cbm = new DefaultComboBoxModel(v);
            this.clienteCombo.setModel(cbm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, String.format("Erro ao ler os Clientes:%s", ex.getMessage()), "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormCliente.class.getName()).log(Level.WARNING, "Erro ao ler os Clientes", ex);
        }
    }

    private void limpatela() {
        this.anoTxt.setText("");
        this.fabricanteTxt.setText("");
        this.modeloTxt.setText("");
        this.kmTxt.setText("");
        this.idTxt.setText("");
        this.clienteCombo.setSelectedItem("");

    }

    private int intCampoTelas(String valor) {
        int ret = 0;
        try {
            ret = Integer.parseInt(valor);
        } catch (NumberFormatException ex) {
        }
        return ret;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoTxt;
    private javax.swing.JComboBox clienteCombo;
    private javax.swing.JButton excluirButton;
    private javax.swing.JTextField fabricanteTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kmTxt;
    private javax.swing.JButton limpaButton;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JButton relaodButton;
    private javax.swing.JButton salvarButton;
    private javax.swing.JTable veiculoTable;
    // End of variables declaration//GEN-END:variables
}
